// scripts/seedEmilyGoal.js
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import dns from 'dns';
import User from '../models/User.js';
import Account from '../models/Account.js';
import Goal from '../models/Goal.js';
import GoalActivity from '../models/GoalActivity.js';
import Transaction from '../models/Transaction.js';

dotenv.config();
dns.setDefaultResultOrder('ipv4first');
dns.setServers(['8.8.8.8', '1.1.1.1']);

// ─────────────────────────────────────────────────────────
//  Configuration
// ─────────────────────────────────────────────────────────
const GOAL_NAME           = 'Porsche 911 Turbo S';
const GOAL_CATEGORY       = 'New Car';
const TARGET_AMOUNT       = 600000;      // $600,000
const CONTRIBUTION_AMOUNT = 50000;       // $50,000 per month
const CONTRIBUTION_FREQ   = 'Monthly';
const CONTRIBUTION_DAY    = 1;           // 1st of every month

// Payments already made — 1st of each month, June → September
// (change these if you want a different history)
const HISTORY_MONTHS = [
  '2026-06-01',
  '2026-07-01',
  '2026-08-01',
  '2026-09-01',
];

const money = (n) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(n ?? 0);

const accountLabel = (acc) =>
  acc
    ? `${acc.subType ? acc.subType + ' ' : ''}${acc.type} •••• ${
        acc.accountNumber ? acc.accountNumber.slice(-4) : ''
      }`
    : '';

const run = async () => {
  await mongoose.connect(process.env.MONGO_URL);
  console.log('✅ Connected\n');

  // ── Resolve Emily ──────────────────────────────────────
  const emily = await User.findOne({ username: 'emilydavis' })
    .select('_id firstName lastName')
    .lean();
  if (!emily) {
    console.error('❌ User "emilydavis" not found');
    process.exit(1);
  }
  console.log(`🎯 User: ${emily.firstName} ${emily.lastName} (${emily._id})\n`);

  // ── Resolve her Checking + High Yield Savings ──────────
  const [checking, savings] = await Promise.all([
    Account.findOne({ userId: emily._id, type: 'Checking' }).lean(),
    Account.findOne({
      userId: emily._id,
      type: 'Savings',
      subType: 'High Yield',
    }).lean(),
  ]);

  if (!checking) {
    console.error('❌ No Checking account found');
    process.exit(1);
  }
  if (!savings) {
    console.error('❌ No High Yield Savings account found');
    process.exit(1);
  }

  console.log(
    `📤 From : ${accountLabel(checking)}  (avail ${money(checking.availableBalance)})`
  );
  console.log(
    `📥 Into : ${accountLabel(savings)}  (bal   ${money(savings.totalBalance)})\n`
  );

  // ── Clean up any prior goal with the same name ─────────
  const existing = await Goal.find({
    userId: emily._id,
    name: GOAL_NAME,
  })
    .select('_id')
    .lean();

  if (existing.length > 0) {
    const ids = existing.map((g) => g._id);
    await GoalActivity.deleteMany({ goalId: { $in: ids } });
    // Also remove the transactions that were generated by a previous run
    await Transaction.deleteMany({ goalId: { $in: ids } });
    await Goal.deleteMany({ _id: { $in: ids } });
    console.log(`🧹 Removed ${ids.length} prior goal(s) + their activity + transactions\n`);
  }

  // ── Target date: one year from today ───────────────────
  const targetDate = new Date();
  targetDate.setFullYear(targetDate.getFullYear() + 1);
  targetDate.setHours(0, 0, 0, 0);

  // ── Create the Goal first (so transactions can reference it) ──
  const goal = await Goal.create({
    userId: emily._id,
    name: GOAL_NAME,
    category: GOAL_CATEGORY,
    currentAmount: 0,
    targetAmount: TARGET_AMOUNT,
    targetDate,

    sourceAccountId: checking._id,
    linkedAccountId: savings._id,
    sourceAccountLabel: accountLabel(checking),
    linkedAccountLabel: accountLabel(savings),

    contributionAmount: CONTRIBUTION_AMOUNT,
    contributionFrequency: CONTRIBUTION_FREQ,
    contributionDay: CONTRIBUTION_DAY,
    nextContributionDate: null, // set after backfill below

    status: 'On Track',
  });

  console.log(`✅ Goal created — ${goal._id}\n`);

  // ── Backfill history: June → September ─────────────────
  let runningTotal = 0;
  let totalMoved = 0;

  for (const dateStr of HISTORY_MONTHS) {
    const payDate = new Date(dateStr + 'T10:00:00Z');

    // 1. Two Transaction rows (debit checking, credit savings)
    await Transaction.create([
      {
        userId: emily._id,
        accountId: checking._id,
        goalId: goal._id,
        description: `Goal Savings — ${GOAL_NAME}`,
        amount: -CONTRIBUTION_AMOUNT,
        type: 'transfer',
        status: 'Completed',
        date: payDate,
      },
      {
        userId: emily._id,
        accountId: savings._id,
        goalId: goal._id,
        description: `Goal Savings — ${GOAL_NAME}`,
        amount: CONTRIBUTION_AMOUNT,
        type: 'transfer',
        status: 'Completed',
        date: payDate,
      },
    ]);

    runningTotal += CONTRIBUTION_AMOUNT;
    totalMoved += CONTRIBUTION_AMOUNT;

    // 2. One GoalActivity row
    await GoalActivity.create({
      userId: emily._id,
      goalId: goal._id,
      date: payDate,
      description: 'Automatic contribution',
      amount: CONTRIBUTION_AMOUNT,
      balance: runningTotal,
      kind: 'auto',
    });

    console.log(
      `   💸 ${dateStr}  -${money(CONTRIBUTION_AMOUNT)}  →  balance ${money(runningTotal)}`
    );
  }

  // ── Adjust account balances to reflect the money movement ──
  await Account.updateOne(
    { _id: checking._id },
    {
      $inc: {
        availableBalance: -totalMoved,
        totalBalance: -totalMoved,
      },
    }
  );
  await Account.updateOne(
    { _id: savings._id },
    {
      $inc: {
        availableBalance: totalMoved,
        totalBalance: totalMoved,
      },
    }
  );

  // ── Update goal with current amount + next contribution ──
  const next = new Date();
  next.setMonth(next.getMonth() + 1);
  next.setDate(CONTRIBUTION_DAY);
  next.setHours(10, 0, 0, 0);

  goal.currentAmount = runningTotal;
  goal.nextContributionDate = next;
  goal.lastContributionDate = new Date(
    HISTORY_MONTHS[HISTORY_MONTHS.length - 1] + 'T10:00:00Z'
  );
  await goal.save();

  // ── Summary ────────────────────────────────────────────
  console.log('\n── Summary ──');
  console.log(`   Goal ID         : ${goal._id}`);
  console.log(`   Name            : ${goal.name}`);
  console.log(`   Category        : ${goal.category}`);
  console.log(`   Target          : ${money(TARGET_AMOUNT)}`);
  console.log(`   Saved so far    : ${money(goal.currentAmount)}`);
  console.log(`   Remaining       : ${money(TARGET_AMOUNT - goal.currentAmount)}`);
  console.log(`   Progress        : ${Math.round((goal.currentAmount / TARGET_AMOUNT) * 100)}%`);
  console.log(`   Target Date     : ${targetDate.toISOString().slice(0, 10)}`);
  console.log(`   Schedule        : ${money(CONTRIBUTION_AMOUNT)} / ${CONTRIBUTION_FREQ}`);
  console.log(`   Next auto-run   : ${next.toISOString().slice(0, 10)}`);
  console.log(`   Payments made   : ${HISTORY_MONTHS.length}`);
  console.log(`   Total moved     : ${money(totalMoved)}`);
  console.log(`   From            : ${accountLabel(checking)}`);
  console.log(`   Into            : ${accountLabel(savings)}`);

  console.log('\n🎉 Done — reload /goals in the browser.');
  await mongoose.disconnect();
  process.exit();
};

run().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});